---
- set_fact:
    _backup_profile_name: "" # Initialize to a blank string

- name: backup-configure | Ensure for backup user is exists
  user: name={{backup_user}}

- name: backup-configure | Ensure for backup directories is exits
  file: path={{item}} state=directory owner={{backup_user}} group={{backup_group}}
  with_items:
  - "{{backup_home}}"
  - "{{backup_work}}"
  - "{{backup_logdir}}"

- name: backup-configure | Install duply
  template: src=duply.sh.j2 dest=/usr/bin/duply owner={{backup_user}} group={{backup_group}} mode=0755

- name: backup-configure | Setup cron
  template: src=cron.j2 dest=/etc/cron.d/{{backup_cron_filename}} owner=root group=root mode=0644
  when: backup_cron|bool

- name: backup-configure | Configure logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/backup owner=root group=root mode=0644

- name: backup-configure | Configure backup profiles
  include_tasks: configure-profile.yml
  with_items: "{{backup_profiles}}"
