---

- include_vars: "{{ansible_distribution}}.yml"

- name: Install dependencies
  apt:
    pkg: ["cron", "gzip", "python-boto", "s3cmd", "ssmtp"]

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}={{backup_duplicity_version}}"
  when: backup_duplicity_version|bool

- name: Install duplicity
  apt: pkg={{backup_duplicity_pkg}}
